In [1]:
import pandas as pd

In [210]:
df20=pd.read_csv('/content/2020 시간 표시 수정.CSV',encoding='cp949')

In [211]:
len(df20)
df20.info()
df20.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2799 entries, 0 to 2798
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   일시       2799 non-null   object
 1   강수량(mm)  1061 non-null   float64
 2   적설(cm)   208 non-null    float64
dtypes: float64(2), object(1)
memory usage: 65.7+ KB

                 일시  강수량(mm)  적설(cm)
0  2020-01-01 00:00      0.0     NaN
1  2020-01-01 01:00      NaN     NaN
2  2020-01-01 02:00      NaN     NaN
3  2020-01-01 03:00      0.0     NaN
4  2020-01-01 04:00      NaN     NaN

In [237]:
import time
import datetime
from datetime import timedelta

d = datetime.datetime(2020,1,1,0,0)
d.strftime('%Y-%m-%d %H:%M')

dtlist=[]
for a in range(365):
    day=d + timedelta(days=a)
    for i in range(24):
        dayhour=day + timedelta(hours=i)
        dayhour.strftime('%Y-%m-%d %H:%M')
        f=str(dayhour)
        dtlist.append(str(f[0:16]))

In [238]:
len(dtlist)

8760

In [239]:
dtdf=pd.DataFrame(dtlist)
dtdf.insert(1,'강수량',"0")
dtdf.insert(2,'적설량',"0")
dtdf.tail()

                     0 강수량 적설량
8755  2020-12-30 19:00   0   0
8756  2020-12-30 20:00   0   0
8757  2020-12-30 21:00   0   0
8758  2020-12-30 22:00   0   0
8759  2020-12-30 23:00   0   0

In [240]:
dtdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8760 non-null   object
 1   강수량     8760 non-null   object
 2   적설량     8760 non-null   object
dtypes: object(3)
memory usage: 205.4+ KB

In [232]:
np.isnan(df20.iloc[0,])

False

In [241]:
import numpy as np
from numpy import NaN
from tqdm import tqdm

for a in  tqdm(range(len(df20))):
    if np.isnan(df20.iloc[a,1]) == True:
        pass
    else:
        n=float(df20.iloc[a,1])
        for b in range(len(dtdf)):
            if df20.iloc[a,0] != dtdf.iloc[b,0]:
                pass
            elif df20.iloc[a,0] == dtdf.iloc[b,0]:
                dtdf.iloc[b,1]=n

100%|██████████| 2799/2799 [08:54<00:00,  5.23it/s]

In [242]:
for a in  tqdm(range(len(df20))):
    if np.isnan(df20.iloc[a,2]) == True:
        pass
    else:
        n=float(df20.iloc[a,2])
        for b in range(len(dtdf)):
            if df20.iloc[a,0] != dtdf.iloc[b,0]:
                pass
            elif df20.iloc[a,0] == dtdf.iloc[b,0]:
                dtdf.iloc[b,2]=n

100%|██████████| 2799/2799 [01:43<00:00, 26.98it/s]

In [243]:
dtdf.head()

                  0  강수량 적설량
0  2020-01-01 00:00  0.0   0
1  2020-01-01 01:00    0   0
2  2020-01-01 02:00    0   0
3  2020-01-01 03:00  0.0   0
4  2020-01-01 04:00    0   0

In [244]:
dtdf.to_csv('dtdf.csv')