In [90]:
import json
from tqdm import tqdm
import numpy as np
import pandas as pd

In [91]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [92]:
%cd /content/drive/MyDrive/멀티캠퍼스 5조/2.데이터

/content/drive/MyDrive/멀티캠퍼스 5조/2.데이터

In [93]:
json = json.load(open('./json/서울행정동_수정.json','r', encoding = 'utf-8'))

In [78]:
features = pd.DataFrame(json['features'])
features = features[['properties', 'geometry']]

In [79]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   properties  423 non-null    object
 1   geometry    423 non-null    object
dtypes: object(2)
memory usage: 6.7+ KB

In [ ]:
allavg=[]
for f in range(len(features)):
    lonlatlst=features.loc[f, 'geometry']['coordinates'][0][0]
    lonsum=0
    latsum=0
    for i in range(len(lonlatlst)):
        lonsum+=lonlatlst[i][0]
        lonavg=lonsum/len(lonlatlst)
        latsum+=lonlatlst[i][1]
        latavg=latsum/len(lonlatlst)
        lonlatavg=[latavg,lonavg]
    allavg.append(lonlatavg)
allavg

In [83]:
df = pd.DataFrame(allavg)

In [84]:
donglst=[]
for f in range(len(features)):
    dong=features.loc[f, 'properties']['동']
    donglst.append(dong)
dongdf=pd.DataFrame(donglst)

In [86]:
df2=pd.concat([dongdf,df],axis=1)
df2.columns = ["동", "Latitude","Longitude "]
df2

         동   Latitude  Longitude
0      사직동  37.575267  126.969738
1      삼청동  37.586728  126.982915
2      부암동  37.597352  126.960548
3      평창동  37.611640  126.970384
4      무악동  37.578839  126.957608
..     ...        ...         ...
418  둔촌제1동  37.521618  127.143993
419  둔촌제2동  37.530555  127.148896
420  암사제1동  37.551118  127.137812
421  천호제2동  37.543261  127.123268
422     길동  37.539585  127.144805

[423 rows x 3 columns]

In [88]:
df2.to_csv('/content/drive/MyDrive/멀티캠퍼스 5조/2.데이터/서울시 행정동 중심좌표.CSV', index = None)